import { Link, useNavigate } from 'react-router';

export function AlgorithmsArticle() {
  const navigate = useNavigate();
  return (
    <article className="c-page-layout c-article-layout"><div className="c-page-container">
      <button className="c-page-back-btn" onClick={() => navigate('/kien-thuc')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="16" height="16" aria-hidden="true"><path d="M19 12H5M12 19l-7-7 7-7" /></svg> Quay lại mục Kiến thức</button>
      <header className="c-page-hero"><div className="c-page-hero-badge">Công nghệ C-checker</div><h1 className="c-page-title">LCS, N-gram và Semantic Similarity hoạt động thế nào?</h1><p className="c-page-subtitle">Vì sao một lượt kiểm tra có thể mất thời gian và mỗi phép đo đóng góp gì vào báo cáo tương đồng tiếng Trung.</p><div className="c-article-byline">Ban biên tập C-checker · Cập nhật 01/09/2026 · 9 phút đọc</div></header>
      <div className="c-page-content c-article-content">
        <section><h2>1. C-checker không chỉ so hai chuỗi văn bản</h2><p>Một công cụ chính tả thường chỉ cần phân tích nội dung người dùng nhập. C-checker phải thực hiện nhiều công đoạn hơn: chia tài liệu thành các khối ngắn, tạo truy vấn tìm nguồn công khai, tải một số trang ứng viên, làm sạch nội dung rồi so sánh từng ứng viên bằng nhiều phép đo. Tốc độ vì thế phụ thuộc cả độ dài tài liệu, số nguồn tìm được, phản hồi của website bên ngoài và tài nguyên xử lý mô hình.</p><div className="c-article-note"><strong>Lưu ý:</strong> thời gian chờ không chỉ đến từ AI. Tìm kiếm và tải các trang nguồn trên Internet thường là phần có độ trễ biến động nhất.</div></section>
        <section><h2>2. LCS: phát hiện chuỗi chung theo đúng thứ tự</h2><p>LCS, viết tắt của Longest Common Subsequence, tìm dãy token chung dài nhất xuất hiện theo cùng thứ tự trong hai đoạn. Các token giống nhau không bắt buộc phải nằm sát nhau, nên LCS vẫn nhận ra trường hợp người viết chèn thêm một vài từ vào câu gốc.</p><p>Trong phiên bản hiện tại, C-checker token hóa văn bản tiếng Trung rồi tính độ dài LCS chia cho độ dài lớn hơn của hai chuỗi token. Thuật toán quy hoạch động cổ điển có chi phí xấp xỉ O(n × m), với n và m là số token của hai đoạn. Vì hệ thống làm việc trên các câu hoặc khối ngắn thay vì so toàn bộ luận văn với toàn bộ trang web trong một lần, chi phí được giới hạn nhưng vẫn tăng theo số ứng viên.</p><p>LCS mạnh khi trật tự từ được giữ lại, nhưng yếu hơn trước cách viết lại làm thay đổi cấu trúc sâu. Điểm cao cũng có thể xuất hiện ở định nghĩa chuẩn hoặc cụm chuyên ngành bắt buộc.</p></section>
        <section><h2>3. N-gram: đo các cụm token liền nhau</h2><p>N-gram tạo những cụm liên tiếp gồm N token. C-checker hiện dùng bigram, tức các cặp token liền nhau, rồi tính mức chồng lấp đối xứng giữa hai tập hợp. Nếu nhiều cặp từ xuất hiện ở cả hai đoạn, điểm N-gram tăng.</p><p>Phép đo này đơn giản và nhanh hơn việc suy luận mô hình ngữ nghĩa. Nó nhạy với sao chép nguyên văn và các chỉnh sửa nhỏ, nhưng giảm mạnh khi người viết đổi nhiều từ, đảo cấu trúc hoặc diễn đạt lại. N-gram cũng không tự hiểu một cụm là trích dẫn hợp lệ hay câu chữ phổ biến.</p></section>
        <section><h2>4. Semantic Similarity: đo độ gần về ý nghĩa</h2><p>C-checker dùng mô hình <code>paraphrase-multilingual-MiniLM-L12-v2</code> để biến hai đoạn thành vector, sau đó tính cosine similarity. Nhờ đó, hai câu không trùng nhiều token vẫn có thể nhận điểm ngữ nghĩa cao nếu mô hình nhận thấy chúng diễn đạt nội dung gần nhau.</p><p>Semantic similarity hữu ích với paraphrase, nhưng không phải máy “phát hiện đạo ý tưởng” tuyệt đối. Hai câu được viết độc lập về cùng một chủ đề có thể gần nhau; câu mơ hồ hoặc quá ngắn cũng dễ thiếu ngữ cảnh. Quan trọng hơn, mô hình chỉ chấm các nguồn mà bước tìm kiếm đã thu được. Nếu nguồn không được lập chỉ mục, nằm sau đăng nhập hoặc không tải được, phép đo ngữ nghĩa không thể tự tìm ra nguồn đó.</p></section>
        <section><h2>5. Contiguous: chuỗi giống nhau liền mạch</h2><p>Ngoài ba chỉ số thường được nhắc đến, C-checker còn tính chuỗi token giống nhau dài nhất và liên tiếp trong cả hai đoạn. Chỉ số Contiguous giúp phân biệt một dãy được chép liền mạch với các token giống nhau nhưng nằm rải rác.</p></section>
        <section><h2>6. Cách kết hợp thành điểm Final</h2><div className="c-guide-table"><div className="c-guide-table-row c-guide-table-header"><span>Chỉ số</span><span>Trọng số hiện tại</span></div><div className="c-guide-table-row"><span>LCS</span><span>35% — trật tự token chung</span></div><div className="c-guide-table-row"><span>N-gram</span><span>20% — cụm token liền nhau</span></div><div className="c-guide-table-row"><span>Semantic</span><span>35% — độ gần về ý nghĩa</span></div><div className="c-guide-table-row"><span>Contiguous</span><span>10% — chuỗi trùng liền mạch</span></div></div><p>C-checker tính cả bốn chỉ số cho mỗi ứng viên rồi cộng theo trọng số trên. Kết quả Final từ 35% mới được giữ lại để hiển thị. Đây là mô hình chấm điểm song song, không phải quy trình trong đó N-gram loại nguồn trước rồi mới chạy LCS và Semantic.</p></section>
        <section><h2>7. Vì sao kết hợp nhiều phép đo?</h2><p>Mỗi chỉ số nhìn văn bản từ một góc khác nhau. LCS và N-gram cung cấp bằng chứng rõ về câu chữ; Semantic bổ sung khả năng nhận ra diễn đạt gần nghĩa; Contiguous nhấn mạnh những chuỗi được giữ nguyên. Kết hợp chúng giúp giảm sự phụ thuộc vào một tín hiệu duy nhất, nhưng không loại bỏ hoàn toàn sai số.</p><p>Khi đọc báo cáo, đừng chỉ nhìn Final. Hãy xem chỉ số nào làm điểm tăng, đọc phần highlight, mở nguồn và kiểm tra trích dẫn. Xem thêm <Link to="/kien-thuc/huong-dan-doc-bao-cao">hướng dẫn đọc báo cáo</Link> và <Link to="/kien-thuc/han-che-va-sai-so">hạn chế của C-checker</Link>.</p></section>
      </div>
    </div></article>
  );
}
