import { Link, useNavigate } from 'react-router';

export function ChineseParaphraseArticle() {
  const navigate = useNavigate();
  return (
    <article className="c-page-layout c-article-layout"><div className="c-page-container">
      <button className="c-page-back-btn" onClick={() => navigate('/kien-thuc')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="16" height="16" aria-hidden="true"><path d="M19 12H5M12 19l-7-7 7-7" /></svg> Quay lại mục Kiến thức</button>
      <header className="c-page-hero"><div className="c-page-hero-badge">Kỹ năng viết học thuật</div><h1 className="c-page-title">Cách paraphrase tiếng Trung đúng cách và tránh đạo văn</h1><p className="c-page-subtitle">Paraphrase là diễn đạt lại sau khi hiểu nguồn, giữ nguyên phạm vi và sắc thái của ý tưởng, đồng thời vẫn ghi nguồn—không phải thay từ để né công cụ.</p><div className="c-article-byline">Ban biên tập C-checker · Cập nhật 01/09/2026 · 10 phút đọc</div></header>
      <div className="c-page-content c-article-content">
        <section><h2>1. Paraphrase không chỉ là đổi từ đồng nghĩa</h2><p>Thay vài từ nhưng giữ nguyên trật tự mệnh đề, ví dụ và cách lập luận vẫn có thể quá sát nguồn. Với tiếng Trung, thay thuật ngữ chuẩn bằng từ gần nghĩa còn dễ tạo lỗi kết hợp từ hoặc làm sai khái niệm.</p><p>C-checker có thể ghi nhận cả khớp chuỗi và sự gần nhau về ngữ nghĩa, nhưng không có công cụ nào quyết định thay người đọc rằng một đoạn paraphrase đã trung thành và trích dẫn đúng.</p></section>
        <section><h2>2. Bốn yêu cầu của một đoạn paraphrase tốt</h2><ol className="c-article-steps"><li><strong>Hiểu ý trước khi viết:</strong> xác định luận điểm, bằng chứng và giới hạn của phát biểu.</li><li><strong>Tổ chức lại theo lập luận của bạn:</strong> chọn thông tin cần dùng, thay đổi trọng tâm và quan hệ giữa các câu khi nguồn cho phép.</li><li><strong>Không thêm mức độ chắc chắn:</strong> “có thể”, “liên quan” và “gây ra” không thể thay thế lẫn nhau.</li><li><strong>Vẫn dẫn nguồn:</strong> câu chữ mới không biến ý tưởng của người khác thành ý tưởng của bạn.</li></ol></section>
        <section><h2>3. Quy trình sáu bước</h2><ol className="c-article-steps"><li>Đọc cả đoạn và tra thuật ngữ chưa rõ.</li><li>Ghi lại ý chính bằng vài từ khóa, không chép nguyên câu.</li><li>Đóng nguồn và viết câu phục vụ mục tiêu đoạn văn của bạn.</li><li>Mở lại nguồn, so sánh phạm vi, quan hệ nhân quả và thái độ của tác giả.</li><li>Giữ nguyên thuật ngữ bắt buộc; sửa cấu trúc còn quá sát.</li><li>Thêm trích dẫn và kiểm tra lại trong ngữ cảnh toàn đoạn.</li></ol></section>
        <section><h2>4. Ví dụ 1: thay cấu trúc nhưng giữ mức độ khẳng định</h2><p><strong>Câu nguồn:</strong> 许多学者认为，数字化教学模式有助于提高留学生的自主学习能力。</p><p><strong>Paraphrase:</strong> 在不少研究者看来，留学生自主学习能力的提升可以得到数字化教学模式的支持（Tác giả, năm）。</p><p>Cả hai câu đều thể hiện đây là quan điểm của nhiều nhà nghiên cứu và chỉ khẳng định tác dụng hỗ trợ. Không nên đổi thành “数字化教学模式决定了……” vì từ “quyết định” mạnh hơn nguồn.</p></section>
        <section><h2>5. Ví dụ 2: cô đọng mô tả phương pháp</h2><p><strong>Câu nguồn:</strong> 研究团队使用问卷调查了300名大学生，并分析了他们使用在线词典的频率。</p><p><strong>Paraphrase:</strong> 该研究通过对300名大学生开展问卷调查，考察了其在线词典的使用频率（Tác giả, năm）。</p><p>Số người, phương pháp và đối tượng đo được giữ nguyên. Bản mới không tự thêm kết quả, tính đại diện hay quan hệ nhân quả.</p></section>
        <section><h2>6. Ví dụ 3: tổng hợp nhiều nguồn</h2><p>Thay vì viết một câu riêng cho từng tác giả, hãy xác định điểm chung và khác biệt: “关于二语词汇学习，部分研究强调显性记忆策略的作用，另一些研究则关注语境输入；近期讨论开始考察两类方法的结合（Tác giả A, năm; Tác giả B, năm; Tác giả C, năm）。”</p><p>Chỉ được viết “phần lớn học giả đồng ý” khi tập tài liệu thực sự hỗ trợ nhận định đó. Không nên biến ba nguồn được chọn thành sự đồng thuận của toàn ngành.</p></section>
        <section><h2>7. Các kỹ thuật có thể dùng thận trọng</h2><ul className="c-guide-list"><li>Chuyển chủ thể của câu khi không làm đổi người thực hiện hành động.</li><li>Gộp hai câu hoặc tách một câu dài để phù hợp mạch lập luận.</li><li>Danh từ hóa khi câu vẫn tự nhiên và không tăng mức độ khẳng định.</li><li>Đổi thứ tự trình bày nguyên nhân–kết quả chỉ khi quan hệ logic được giữ nguyên.</li><li>Tóm tắt thay vì giữ mọi chi tiết, nhưng không bỏ điều kiện hoặc giới hạn quan trọng.</li></ul></section>
        <section><h2>8. Checklist sau khi viết lại</h2><ul className="c-check-list"><li>Câu mới có giữ đúng chủ thể, thời gian, phạm vi và mức độ chắc chắn không?</li><li>Có tự thêm quan hệ nhân quả, đánh giá hoặc kết quả nào không?</li><li>Thuật ngữ chuyên ngành có còn chính xác và tự nhiên không?</li><li>Cấu trúc có thực sự là của bạn hay chỉ đổi vài từ?</li><li>Nguồn đã được ghi đúng vị trí và đúng chuẩn chưa?</li></ul><p>Sau khi hoàn thiện, có thể dùng C-checker để tìm những câu còn quá gần nguồn, rồi thẩm định thủ công. Xem thêm <Link to="/kien-thuc/ty-le-tuong-dong-va-dao-van-khac-nhau-nhu-the-nao">sự khác nhau giữa tương đồng và đạo văn</Link>.</p></section>
      </div>
    </div></article>
  );
}
