import { Link, useNavigate } from 'react-router';

export function ChineseComparisonArticle() {
  const navigate = useNavigate();
  return (
    <article className="c-page-layout c-article-layout"><div className="c-page-container">
      <button className="c-page-back-btn" onClick={() => navigate('/kien-thuc')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="16" height="16" aria-hidden="true"><path d="M19 12H5M12 19l-7-7 7-7" /></svg> Quay lại mục Kiến thức</button>
      <header className="c-page-hero"><div className="c-page-hero-badge">Đặc thù xử lý Hán ngữ</div><h1 className="c-page-title">Vì sao kiểm tra đạo văn tiếng Trung khó hơn tiếng Anh, tiếng Việt?</h1><p className="c-page-subtitle">Sự khác biệt về ranh giới từ, hệ chữ, ngữ cảnh và dữ liệu đối chiếu khiến các thuật toán dành cho văn bản Latin không thể áp dụng nguyên vẹn cho tiếng Trung.</p><div className="c-article-byline">Ban biên tập C-checker · Cập nhật 01/09/2026 · 8 phút đọc</div></header>
      <div className="c-page-content c-article-content">
        <section><h2>1. Không có khoảng trắng phân tách từ</h2><p>Tiếng Anh và tiếng Việt dùng khoảng trắng làm dấu hiệu hữu ích để xác định đơn vị từ. Tiếng Trung viết các Hán tự liền nhau, nên hệ thống phải thực hiện phân tách từ (分词) trước khi tính N-gram hoặc đối chiếu token.</p><p>Một chuỗi có thể được tách khác nhau tùy ngữ cảnh. Nếu ranh giới từ sai, các phép đo phía sau cũng bị ảnh hưởng. Đây là lý do công cụ chỉ tách theo ký tự hoặc dùng bộ xử lý thiết kế cho tiếng Anh thường cho kết quả kém ổn định.</p></section>
        <section><h2>2. Một chữ có nhiều cách đọc và nghĩa</h2><p>Nhiều Hán tự là đa âm, đa nghĩa. So khớp ký tự có thể nhận ra hình thức giống nhau nhưng không biết chúng đang mang cùng nghĩa hay không. Ngược lại, hai câu diễn đạt cùng ý có thể dùng từ khác nhau và không tạo nhiều chuỗi ký tự chung. Phân tích ngữ cảnh vì thế quan trọng hơn việc chỉ đếm ký tự.</p></section>
        <section><h2>3. Giản thể và phồn thể tồn tại song song</h2><p>Cùng một nội dung có thể xuất hiện dưới dạng giản thể hoặc phồn thể. Nếu không chuẩn hóa hai hệ chữ, phép so khớp trực tiếp có thể bỏ sót nội dung tương đương. Tuy nhiên, chuyển đổi cũng không phải lúc nào là quan hệ một-một; một số chữ cần ngữ cảnh để chọn dạng phù hợp.</p></section>
        <section><h2>4. Có thể thay đổi trật tự mà vẫn giữ ý</h2><p>Trạng ngữ, bổ ngữ và một số cụm thành phần trong tiếng Trung có thể được sắp xếp lại mà câu vẫn truyền đạt nội dung gần nhau. Việc thay từ, đảo cụm hoặc rút gọn làm LCS giảm nhanh dù ý chính không đổi. Phép đo ngữ nghĩa hỗ trợ trường hợp này nhưng cũng có thể cảnh báo nhầm hai câu độc lập cùng nói về một chủ đề.</p></section>
        <section><h2>5. Thành ngữ và cụm cố định xuất hiện dày đặc</h2><p>成语, 谚语, 俗语, thuật ngữ và cấu trúc học thuật được lặp lại hợp pháp trong nhiều tài liệu. Nếu coi mọi cụm giống nhau là bằng chứng sao chép, hệ thống sẽ tạo nhiều dương tính giả. Người đọc báo cáo cần phân biệt vốn chung của ngôn ngữ với cách diễn đạt mang dấu ấn của một tác giả.</p></section>
        <section><h2>6. Dữ liệu học thuật bị phân mảnh</h2><p>Nguồn tiếng Trung nằm trên nhiều nền tảng, thư viện, kho luận văn và cơ sở dữ liệu có cơ chế truy cập khác nhau. Một công cụ tìm kiếm trên web công khai không thể bao phủ toàn bộ sách, luận văn hoặc bài báo sau đăng nhập. Vì vậy, không tìm thấy nguồn không đồng nghĩa chắc chắn nguyên bản.</p></section>
        <section><h2>7. Một hệ thống phù hợp cần những gì?</h2><ul className="c-guide-list"><li>Chuẩn hóa Unicode, dấu câu và các biến thể chữ.</li><li>Phân tách từ phù hợp với tiếng Trung và giữ được vị trí trong văn bản gốc.</li><li>Kết hợp bằng chứng ký tự, token, chuỗi liên tiếp và ngữ nghĩa.</li><li>Nhận diện các cụm phổ biến để hạn chế cảnh báo nhầm.</li><li>Hiển thị nguồn và ngữ cảnh để con người thẩm định.</li></ul><p>C-checker kết hợp nhiều phép đo nhưng vẫn phụ thuộc vào nguồn web có thể tìm và truy cập. Xem <Link to="/kien-thuc/lcs-ngram-semantic-similarity">cách các chỉ số hoạt động</Link> và <Link to="/kien-thuc/han-che-va-sai-so">các giới hạn cần lưu ý</Link>.</p></section>
        <section><h2>Kết luận</h2><p>Kiểm tra tiếng Trung khó không phải vì một nguyên nhân duy nhất, mà do ranh giới từ, ngữ nghĩa theo ngữ cảnh, hai hệ chữ, cụm cố định và dữ liệu phân mảnh cùng tác động. Kết quả phù hợp nhất nên được dùng như bản đồ để rà soát nguồn, không phải phán quyết tự động về đạo văn.</p></section>
      </div>
    </div></article>
  );
}
