import { Link, useNavigate } from 'react-router';

export function IntentionalPlagiarismArticle() {
  const navigate = useNavigate();
  return (
    <article className="c-page-layout c-article-layout"><div className="c-page-container">
      <button className="c-page-back-btn" onClick={() => navigate('/kien-thuc')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="16" height="16" aria-hidden="true"><path d="M19 12H5M12 19l-7-7 7-7" /></svg> Quay lại mục Kiến thức</button>
      <header className="c-page-hero"><div className="c-page-hero-badge">Trung thực học thuật</div><h1 className="c-page-title">Phân biệt đạo văn vô ý và cố ý</h1><p className="c-page-subtitle">Hai trường hợp khác nhau về ý định nhưng đều cần được nhận diện và sửa đúng cách thay vì chỉ tìm cách làm giảm tỷ lệ tương đồng.</p><div className="c-article-byline">Ban biên tập C-checker · Cập nhật 01/09/2026 · 8 phút đọc</div></header>
      <div className="c-page-content c-article-content">
        <section><h2>1. Đạo văn cố ý là gì?</h2><p>Đạo văn cố ý xảy ra khi người viết biết mình đang sử dụng nội dung hoặc công sức của người khác nhưng vẫn trình bày như sản phẩm của chính mình. Các biểu hiện thường gặp gồm:</p><ul className="c-guide-list"><li>Sao chép nguyên đoạn mà không ghi nguồn.</li><li>Mua bài, thuê viết hộ hoặc nộp bài của người khác.</li><li>Cố tình bỏ ngoặc kép hoặc chú thích của một đoạn trích.</li><li>Thay từ và đảo câu máy móc chỉ để né công cụ, trong khi giữ nguyên ý tưởng và cấu trúc nguồn.</li></ul><p>Áp lực thời gian hay thiếu kỹ năng có thể giải thích hoàn cảnh, nhưng không biến hành vi có chủ đích thành sử dụng nguồn hợp lệ.</p></section>
        <section><h2>2. Đạo văn vô ý là gì?</h2><p>Đạo văn vô ý không xuất phát từ ý định gian lận mà thường do người viết chưa hiểu hoặc áp dụng sai quy tắc nguồn:</p><ul className="c-guide-list"><li><strong>Ghi nhớ câu chữ đã đọc:</strong> viết lại gần nguyên văn mà tưởng đó là cách diễn đạt của mình.</li><li><strong>Paraphrase chưa đủ:</strong> chỉ thay một vài từ nhưng giữ cấu trúc và trình tự ý của nguồn.</li><li><strong>Nhầm kiến thức phổ thông:</strong> không dẫn một định nghĩa hoặc cách diễn đạt thực chất thuộc về tác giả cụ thể.</li><li><strong>Lẫn lộn cụm cố định và câu riêng:</strong> khó xác định ranh giới giữa thành ngữ, thuật ngữ chung với đoạn có dấu ấn tác giả.</li><li><strong>Dùng nguồn thứ cấp:</strong> chép lại trích dẫn qua một bài khác mà không kiểm tra tài liệu gốc.</li></ul></section>
        <section><h2>3. Vì sao cần phân biệt?</h2><p>Ý định có thể ảnh hưởng đến cách một cơ sở giáo dục xem xét vụ việc, nhưng quy định cụ thể khác nhau và quyết định không nên chỉ dựa trên phần trăm từ công cụ. Với người viết, việc xác định nguyên nhân giúp chọn cách khắc phục phù hợp: học lại cách trích dẫn và paraphrase nếu thiếu kỹ năng; thay đổi hành vi và quy trình làm việc nếu đã cố tình sao chép.</p><div className="c-article-note"><strong>Không nên tự kết luận ý định của người khác từ báo cáo.</strong> Việc đánh giá cần dựa trên văn bản, lịch sử làm bài, quy định áp dụng và cơ hội giải trình của tác giả.</div></section>
        <section><h2>4. Công cụ có phân biệt được hai loại không?</h2><p>Không. Công cụ đối chiếu chỉ tìm dấu hiệu tương đồng về câu chữ hoặc ý nghĩa. Cùng một đoạn được đánh dấu có thể là sao chép cố ý, trích dẫn thiếu ngoặc kép, lỗi ghi nguồn hoặc một cụm diễn đạt phổ biến. Thuật toán không quan sát được ý định và quá trình viết.</p><p>Vì vậy, kết quả C-checker nên được diễn đạt là “phát hiện nội dung tương đồng với nguồn”, không phải “xác định người viết cố ý đạo văn”.</p></section>
        <section><h2>5. Cách phòng tránh đạo văn vô ý</h2><ol className="c-article-steps"><li><strong>Ghi nguồn ngay khi đọc.</strong> Lưu tác giả, tiêu đề, năm, URL và trang thay vì bổ sung vào phút cuối.</li><li><strong>Đánh dấu rõ ghi chú trực tiếp.</strong> Phân biệt câu chép nguyên văn với phần tóm tắt của chính mình.</li><li><strong>Paraphrase sau khi hiểu.</strong> Đóng nguồn, viết lại lập luận bằng cấu trúc của mình rồi mở lại để kiểm tra độ chính xác.</li><li><strong>Dẫn nguồn cho cả ý tưởng.</strong> Thay đổi câu chữ không làm mất nghĩa vụ ghi nhận nguồn gốc ý tưởng.</li><li><strong>Rà soát trước khi nộp.</strong> Mở từng vị trí được đánh dấu và sửa trích dẫn thay vì chỉ thay từ để giảm phần trăm.</li></ol></section>
        <section><h2>6. Khi phát hiện một đoạn có vấn đề</h2><ul className="c-guide-list"><li>Nếu cần giữ nguyên câu chữ, đặt trong ngoặc kép hoặc định dạng trích dẫn khối và ghi nguồn theo quy chuẩn.</li><li>Nếu chỉ cần ý tưởng, đọc hiểu rồi diễn đạt lại thực chất, đồng thời vẫn dẫn nguồn.</li><li>Nếu đoạn không đóng góp cho lập luận, cân nhắc loại bỏ.</li><li>Nếu không tìm được nguồn gốc ban đầu, đừng khẳng định thông tin cho đến khi kiểm chứng được.</li></ul></section>
        <section><h2>Kết luận</h2><p>Đạo văn cố ý và vô ý khác nhau ở ý định, nhưng đều làm suy giảm tính minh bạch nếu không được sửa. Cách phòng tránh bền vững không phải né chỉ số, mà là quản lý nguồn, hiểu nội dung và ghi nhận đóng góp của người khác một cách nhất quán.</p><p>Xem thêm <Link to="/kien-thuc/cach-nhan-biet-dao-van-tieng-trung">cách nhận biết các hình thức đạo văn tiếng Trung</Link> và <Link to="/kien-thuc/huong-dan-doc-bao-cao">hướng dẫn đọc báo cáo</Link>.</p></section>
      </div>
    </div></article>
  );
}
