import { Link, useNavigate } from 'react-router';

export function RecognizeChinesePlagiarismArticle() {
  const navigate = useNavigate();
  return (
    <article className="c-page-layout c-article-layout"><div className="c-page-container">
      <button className="c-page-back-btn" onClick={() => navigate('/kien-thuc')}><span aria-hidden="true">←</span> Quay lại mục Kiến thức</button>
      <header className="c-page-hero"><div className="c-page-hero-badge">Liêm chính học thuật</div><h1 className="c-page-title">Cách nhận biết đạo văn trong văn bản tiếng Trung</h1><p className="c-page-subtitle">Những hình thức thường gặp, dấu hiệu cần kiểm tra và cách sử dụng nguồn mà vẫn giữ được tính nguyên bản.</p><div className="c-article-byline">Ban biên tập C-checker · Cập nhật 01/09/2026 · 10 phút đọc</div></header>
      <div className="c-page-content c-article-content">
        <section><h2>1. Tương đồng không đồng nghĩa với đạo văn</h2><p>Đạo văn liên quan đến việc sử dụng câu chữ, dữ liệu, cấu trúc lập luận hoặc ý tưởng của người khác mà không ghi nhận phù hợp. Một đoạn có tỷ lệ tương đồng cao vẫn có thể là trích dẫn hợp lệ; ngược lại, đoạn gần như không trùng chữ vẫn có thể thiếu ghi nguồn cho ý tưởng. Vì vậy, cần kết hợp phần mềm với đọc hiểu và quy định trích dẫn của cơ sở đào tạo.</p></section>
        <section><h2>2. Các hình thức thường gặp</h2><div className="c-about-tech-grid"><div className="c-about-tech-card c-about-tech-card--blue"><div className="c-about-tech-icon">逐</div><h3>Sao chép nguyên văn</h3><p>Giữ nguyên toàn bộ hoặc phần lớn câu, đoạn mà không dùng ngoặc kép và không dẫn nguồn.</p></div><div className="c-about-tech-card c-about-tech-card--purple"><div className="c-about-tech-icon">改</div><h3>Diễn đạt lại hời hợt</h3><p>Thay một số từ đồng nghĩa nhưng giữ cấu trúc, trình tự lập luận và cách triển khai của nguồn.</p></div><div className="c-about-tech-card c-about-tech-card--green"><div className="c-about-tech-icon">思</div><h3>Sử dụng ý tưởng không dẫn nguồn</h3><p>Lấy khung phân tích, số liệu hoặc phương pháp đặc thù dù câu chữ đã được viết lại.</p></div><div className="c-about-tech-card c-about-tech-card--amber"><div className="c-about-tech-icon">自</div><h3>Tái sử dụng tác phẩm của chính mình</h3><p>Dùng lại phần đáng kể từ bài đã công bố mà không thông báo, khi quy định xuất bản yêu cầu công khai.</p></div></div></section>
        <section><h2>3. Dấu hiệu nên kiểm tra thêm</h2><ul className="c-guide-list"><li>Văn phong, mức độ học thuật hoặc cách dùng thuật ngữ thay đổi đột ngột.</li><li>Giản thể và phồn thể, cách diễn đạt Đại lục, Đài Loan hoặc Hồng Kông xen kẽ không có lý do.</li><li>Số liệu, tên riêng và mốc thời gian cụ thể xuất hiện nhưng không có nguồn.</li><li>Một đoạn trình bày hoàn chỉnh nhưng không liên kết logic với phần trước và sau.</li><li>Tài liệu tham khảo tồn tại trong danh mục nhưng không được dẫn ở nội dung, hoặc ngược lại.</li><li>Câu dịch có cấu trúc bất thường, gợi ý nội dung được chuyển từ ngoại ngữ mà chưa ghi nhận nguồn.</li></ul><p>Đây chỉ là tín hiệu điều tra, không phải bằng chứng. Văn phong có thể thay đổi vì nhiều tác giả cùng viết, vì bản dịch hoặc do phần phương pháp cần ngôn ngữ chuẩn hóa.</p></section>
        <section><h2>4. Kiểm tra thủ công theo từng bước</h2><ol className="c-article-steps"><li><strong>Chọn cụm đặc trưng.</strong> Lấy khoảng 10–15 chữ có tên riêng, số liệu hoặc cách diễn đạt ít phổ biến.</li><li><strong>Tìm chính xác.</strong> Đặt cụm trong dấu ngoặc kép trên công cụ tìm kiếm; thử cả giản thể và phồn thể khi cần.</li><li><strong>So hai văn bản.</strong> Không chỉ so từ, hãy xem thứ tự luận điểm, ví dụ và kết luận.</li><li><strong>Xác minh nguồn gốc.</strong> Kiểm tra tác giả, ngày công bố và liệu trang tìm thấy có sao chép từ một nguồn sớm hơn.</li><li><strong>Kiểm tra trích dẫn.</strong> Đối chiếu nội dung trích với bản gốc và chuẩn trích dẫn được yêu cầu.</li></ol></section>
        <section><h2>5. Đọc tỷ lệ tương đồng đúng cách</h2><p>Tỷ lệ của mỗi hệ thống phụ thuộc kho dữ liệu, cách tách văn bản, ngưỡng và việc loại trừ trích dẫn. Không có một con số chung áp dụng cho mọi ngành hoặc mọi trường. Cần ưu tiên các đoạn dài, đặc thù, không dẫn nguồn thay vì cố giảm mọi cụm trùng.</p><p>Một bài có tỷ lệ thấp vẫn cần xem xét đạo ý tưởng hoặc nguồn không nằm trong kho đối chiếu. Một bài có tỷ lệ cao có thể chứa nhiều trích dẫn trực tiếp hợp lệ, biểu mẫu hoặc thuật ngữ chuẩn. Xem <Link to="/kien-thuc/huong-dan-doc-bao-cao">hướng dẫn đọc báo cáo C-checker</Link> để hiểu từng chỉ số.</p></section>
        <section><h2>6. Trích dẫn và diễn giải đúng</h2><ul className="c-guide-list"><li>Ghi tác giả, tài liệu, năm và thông tin truy xuất theo chuẩn được yêu cầu.</li><li>Đặt phần trích nguyên văn trong ngoặc kép hoặc khối trích dẫn; không chỉnh câu mà vẫn gọi là nguyên văn.</li><li>Khi diễn giải, đọc hiểu rồi viết lại lập luận bằng cấu trúc của mình, đồng thời vẫn dẫn nguồn ý tưởng.</li><li>Trình bày rõ nguồn của bảng, hình, dữ liệu, bản dịch và phương pháp.</li><li>Đóng góp phân tích riêng thay vì ghép các đoạn trích thành toàn bộ bài viết.</li></ul></section>
        <section><h2>7. Checklist trước khi nộp</h2><ul className="c-guide-list"><li>Mọi số liệu và khẳng định chuyên biệt đều có nguồn kiểm chứng.</li><li>Trích dẫn trực tiếp được đánh dấu và không chiếm tỷ trọng bất hợp lý.</li><li>Danh mục tài liệu tham khảo khớp với các nguồn xuất hiện trong bài.</li><li>Các đoạn được công cụ đánh dấu đã được mở nguồn và đọc trong ngữ cảnh.</li><li>Bản cuối được rà soát theo quy định cụ thể của trường, tạp chí hoặc đơn vị xuất bản.</li></ul></section>
      </div>
    </div></article>
  );
}
