import { Link, useNavigate } from 'react-router';

export function SimilarityVsPlagiarismArticle() {
  const navigate = useNavigate();
  return (
    <article className="c-page-layout c-article-layout"><div className="c-page-container">
      <button className="c-page-back-btn" onClick={() => navigate('/kien-thuc')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="16" height="16" aria-hidden="true"><path d="M19 12H5M12 19l-7-7 7-7" /></svg> Quay lại mục Kiến thức</button>
      <header className="c-page-hero"><div className="c-page-hero-badge">Hiểu đúng kết quả</div><h1 className="c-page-title">Tỷ lệ tương đồng và đạo văn khác nhau như thế nào?</h1><p className="c-page-subtitle">Kết quả 20% tương đồng không có nghĩa 20% bài viết là đạo văn. Một bên là tín hiệu kỹ thuật; bên còn lại cần đánh giá nguồn, ngữ cảnh và quy tắc học thuật.</p><div className="c-article-byline">Ban biên tập C-checker · Cập nhật 01/09/2026 · 7 phút đọc</div></header>
      <div className="c-page-content c-article-content">
        <section><h2>1. Tỷ lệ tương đồng là gì?</h2><p>Tỷ lệ tương đồng là kết quả được tạo từ dữ liệu nguồn mà hệ thống tìm thấy và các phép so khớp như LCS, N-gram, chuỗi liên tiếp và biểu diễn ngữ nghĩa. Nó cho biết mức độ văn bản có dấu hiệu gần với nguồn đối chiếu trong lần kiểm tra đó.</p><p>Con số này phụ thuộc vào nguồn có thể truy cập, cách chia câu, ngưỡng hiển thị và thuật toán. Vì vậy, đây là phép đo kỹ thuật hữu ích nhưng không phải bằng chứng khách quan tuyệt đối.</p></section>
        <section><h2>2. Vì sao nội dung hợp lệ vẫn có thể tương đồng?</h2><ul className="c-guide-list"><li>Tên tổ chức, đề tài và thông tin cố định.</li><li>Thuật ngữ, thành ngữ hoặc cấu trúc học thuật phổ biến.</li><li>Định nghĩa và trích dẫn trực tiếp đã ghi nguồn.</li><li>Tên tác giả, tác phẩm và dữ kiện thư mục.</li><li>Câu hỏi khảo sát hoặc thang đo được sử dụng hợp pháp và có dẫn nguồn.</li></ul><p>C-checker có thể đánh dấu những nội dung này vì thuật toán nhận diện sự giống nhau, không tự biết người viết đã tuân thủ toàn bộ quy tắc trích dẫn hay chưa.</p></section>
        <section><h2>3. Đạo văn là gì?</h2><p>Đạo văn thường liên quan đến việc sử dụng câu chữ, ý tưởng, dữ liệu hoặc cấu trúc của người khác mà không ghi nhận nguồn phù hợp. Việc xác định cần xem xét nội dung cụ thể, quy định áp dụng, lịch sử hình thành bài viết và lời giải trình của tác giả.</p><div className="c-article-note"><strong>Công cụ không thể phán đoán ý định.</strong> Báo cáo tương đồng không đủ để kết luận một người cố ý gian lận. Quyết định có ảnh hưởng đến điểm số hoặc kỷ luật cần do người có trách nhiệm thẩm định.</div></section>
        <section><h2>4. So sánh nhanh</h2><div className="c-article-table-wrap"><table className="c-article-table"><thead><tr><th>Tiêu chí</th><th>Tương đồng</th><th>Đạo văn</th></tr></thead><tbody><tr><td>Bản chất</td><td>Tín hiệu từ phép so khớp</td><td>Vấn đề sử dụng nguồn và liêm chính</td></tr><tr><td>Ai phát hiện?</td><td>Hệ thống tìm nguồn và tính điểm</td><td>Con người đánh giá theo quy định</td></tr><tr><td>Có gồm trích dẫn hợp lệ?</td><td>Có thể có</td><td>Không mặc nhiên là vi phạm</td></tr><tr><td>Có suy ra ý định?</td><td>Không</td><td>Cần bằng chứng và thẩm định</td></tr><tr><td>Cách xử lý</td><td>Mở nguồn và phân loại</td><td>Sửa nguồn, nội dung và quy trình viết</td></tr></tbody></table></div></section>
        <section><h2>5. Ba tình huống dễ nhầm</h2><ul className="c-guide-list"><li><strong>Tỷ lệ tương đối cao nhưng có thể hợp lệ:</strong> tài liệu có nhiều trích dẫn trực tiếp, ngữ liệu và thông tin thư mục được ghi nguồn đầy đủ.</li><li><strong>Tỷ lệ thấp nhưng vẫn có vấn đề:</strong> một ý tưởng hoặc tập dữ liệu quan trọng bị sử dụng không dẫn nguồn, dù câu chữ đã thay đổi.</li><li><strong>Sai sót vô ý:</strong> người viết ghi nguồn chưa đủ, quên ngoặc kép hoặc paraphrase quá sát cấu trúc gốc.</li></ul></section>
        <section><h2>6. Cách dùng báo cáo đúng mục đích</h2><ol className="c-article-steps"><li>Xem tỷ lệ toàn bài để ước lượng phạm vi cần rà soát.</li><li>Đọc từng câu được tô và mở nguồn liên quan.</li><li>Kiểm tra phần trùng có phải thuật ngữ, trích dẫn hoặc dữ kiện cố định không.</li><li>Thêm nguồn, dùng trích dẫn trực tiếp, paraphrase thực chất hoặc loại bỏ nội dung không cần thiết.</li><li>Đối chiếu quy định của nơi nhận bài trước khi đưa ra kết luận.</li></ol><p>Đọc tiếp <Link to="/kien-thuc/dao-van-vo-y-va-co-y">phân biệt đạo văn vô ý và cố ý</Link> và <Link to="/kien-thuc/huong-dan-doc-bao-cao">hướng dẫn đọc báo cáo C-checker</Link>.</p></section>
      </div>
    </div></article>
  );
}
