import { Link, useNavigate } from 'react-router';

export function ThesisSectionsArticle() {
  const navigate = useNavigate();
  return (
    <article className="c-page-layout c-article-layout"><div className="c-page-container">
      <button className="c-page-back-btn" onClick={() => navigate('/kien-thuc')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="16" height="16" aria-hidden="true"><path d="M19 12H5M12 19l-7-7 7-7" /></svg> Quay lại mục Kiến thức</button>
      <header className="c-page-hero"><div className="c-page-hero-badge">Rà soát luận văn</div><h1 className="c-page-title">Những phần nào trong luận văn thường bị báo trùng?</h1><p className="c-page-subtitle">Mỗi phần của luận văn có lý do tương đồng khác nhau. Điều cần làm không phải ép từng chương về một tỷ lệ cố định, mà là đọc đúng ngữ cảnh và xử lý nguồn minh bạch.</p><div className="c-article-byline">Ban biên tập C-checker · Cập nhật 01/09/2026 · 8 phút đọc</div></header>
      <div className="c-page-content c-article-content">
        <section><h2>1. Tổng quan nghiên cứu và cơ sở lý luận</h2><p>文献综述 và phần cơ sở lý luận phải nhắc lại khái niệm, trường phái và kết quả của các tác giả đi trước, nên thường xuất hiện nhiều cụm gần với nguồn. Rủi ro không nằm ở việc có trích dẫn, mà ở cách liệt kê từng tài liệu theo kiểu chép–tóm tắt mà thiếu tổng hợp.</p><p>Hãy tổ chức theo chủ đề, so sánh điểm thống nhất và khác biệt, chỉ ra khoảng trống nghiên cứu rồi ghi nguồn cho từng nhóm nhận định. Phần bình luận của người viết cần được phân biệt rõ với kết luận của tài liệu tham khảo.</p></section>
        <section><h2>2. Khái niệm và định nghĩa chuyên ngành</h2><p>Định nghĩa chuẩn thường có câu chữ tương đối cố định. Nếu cần giữ nguyên, hãy dùng ngoặc kép hoặc định dạng trích dẫn khối theo quy định của nơi nộp bài, kèm tác giả, năm và số trang khi có. Sau đó giải thích vì sao định nghĩa được chọn và được áp dụng như thế nào trong đề tài.</p><p>Không nên thay thuật ngữ bằng từ gần nghĩa chỉ để giảm tỷ lệ, vì việc đó có thể làm sai phạm vi khái niệm.</p></section>
        <section><h2>3. Phương pháp nghiên cứu</h2><p>Mô tả khảo sát, thí nghiệm, phân tích khối liệu hay phép kiểm định thường có cấu trúc quen thuộc. Thay vì sao chép phần phương pháp của một nghiên cứu khác, hãy mô tả chính xác quy trình của mình: đối tượng, thời gian, tiêu chí chọn mẫu, công cụ, biến số và cách xử lý dữ liệu.</p><p>Nếu phương pháp, thang đo hoặc bộ câu hỏi được kế thừa, cần ghi nguồn và mô tả những điều chỉnh đã thực hiện.</p></section>
        <section><h2>4. Bảng hỏi, ngữ liệu và phụ lục</h2><p>Thang đo chuẩn, câu hỏi kế thừa và ngữ liệu trích từ nguồn khác có thể tạo nhiều câu giống nhau. Đưa tài liệu dài vào phụ lục giúp thân bài dễ đọc hơn, nhưng không tự động làm nội dung được miễn trừ. Vẫn phải ghi nguồn, quyền sử dụng và những sửa đổi đã thực hiện.</p><div className="c-article-note"><strong>Lưu ý về C-checker:</strong> hệ thống phân tích phần văn bản được gửi lên và hiện chưa tự động loại trừ mọi trang bìa, phụ lục hoặc danh mục tài liệu tham khảo. Người dùng phải đọc báo cáo theo cấu trúc tài liệu.</div></section>
        <section><h2>5. Danh mục tài liệu tham khảo</h2><p>Tên tác giả, tiêu đề, nhà xuất bản và DOI là thông tin cố định nên có thể giống nhiều tài liệu khác. Không được sửa những dữ kiện này để giảm tỷ lệ. Hãy bảo đảm mỗi nguồn trong danh mục xuất hiện trong thân bài và định dạng đúng hướng dẫn của trường hoặc tạp chí.</p></section>
        <section><h2>6. Phân tích kết quả và kết luận</h2><p>Đây là nơi thể hiện đóng góp của người viết nên những đoạn dài giống nguồn cần được kiểm tra đặc biệt. Tuy nhiên, không có yêu cầu phổ quát rằng phần này phải đạt 0% hay một mốc cụ thể. Tên biến, mô tả phép đo và cách nhắc lại câu hỏi nghiên cứu vẫn có thể tạo tương đồng hợp lý.</p><p>Điều quan trọng là dữ liệu được trình bày trung thực, lập luận xuất phát từ kết quả của đề tài và mọi so sánh với nghiên cứu trước đều được dẫn nguồn.</p></section>
        <section><h2>7. Thứ tự rà soát thực tế</h2><ol className="c-article-steps"><li>Ưu tiên câu dài, trùng nguyên văn hoặc cùng tập trung vào một nguồn.</li><li>Kiểm tra trước phần phân tích, bàn luận và kết luận.</li><li>Phân loại trích dẫn hợp lệ, thuật ngữ cố định và nội dung chưa ghi nguồn.</li><li>Sửa trích dẫn hoặc diễn giải; không thay dữ kiện thư mục và thuật ngữ chuẩn.</li><li>Kiểm tra lại toàn đoạn để bảo đảm mạch lập luận không bị phá vỡ.</li></ol><p>Xem thêm <Link to="/kien-thuc/cach-xu-ly-tung-cau-bi-c-checker-danh-dau">cách xử lý từng câu được đánh dấu</Link> và <Link to="/kien-thuc/bao-nhieu-phan-tram-trung-lap-thi-yen-tam">cách đánh giá tỷ lệ toàn bài</Link>.</p></section>
      </div>
    </div></article>
  );
}
