import { Link, useNavigate } from 'react-router';

export function ThesisChecklistArticle() {
  const navigate = useNavigate();
  return (
    <article className="c-page-layout c-article-layout"><div className="c-page-container">
      <button className="c-page-back-btn" onClick={() => navigate('/kien-thuc')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="16" height="16" aria-hidden="true"><path d="M19 12H5M12 19l-7-7 7-7" /></svg> Quay lại mục Kiến thức</button>
      <header className="c-page-hero"><div className="c-page-hero-badge">Checklist trước khi nộp</div><h1 className="c-page-title">Checklist kiểm tra luận văn tiếng Trung trước khi nộp</h1><p className="c-page-subtitle">Một danh sách rà soát thực tế cho trích dẫn, hệ chữ, cấu trúc, dữ liệu và báo cáo tương đồng—luôn đặt quy định của trường lên trước hướng dẫn chung.</p><div className="c-article-byline">Ban biên tập C-checker · Cập nhật 01/09/2026 · 9 phút đọc</div></header>
      <div className="c-page-content c-article-content">
        <section><div className="c-article-note"><strong>Trước khi bắt đầu:</strong> xin mẫu luận văn và hướng dẫn chính thức từ khoa hoặc cơ sở đào tạo. Font, cỡ chữ, giãn dòng, chuẩn trích dẫn và thứ tự tài liệu tham khảo không giống nhau ở mọi nơi.</div></section>
        <section><h2>1. Trích dẫn và tài liệu tham khảo</h2><ul className="c-check-list"><li>Trích dẫn trực tiếp dùng đúng dấu ngoặc và định dạng mà trường yêu cầu.</li><li>Mỗi nhận định, số liệu, mô hình hoặc bảng kế thừa đều có nguồn tại vị trí sử dụng.</li><li>Mỗi trích dẫn trong thân bài có mục tương ứng trong danh mục và ngược lại.</li><li>Tên tác giả, năm, tiêu đề, nhà xuất bản, số trang, DOI hoặc URL đã được đối chiếu với nguồn gốc.</li><li>Toàn bài dùng nhất quán một chuẩn như APA, GB/T 7714 hoặc chuẩn riêng của trường.</li><li>Nguồn thứ cấp được ghi rõ; ưu tiên kiểm tra tài liệu gốc khi có thể.</li></ul></section>
        <section><h2>2. Hệ chữ, ngôn ngữ và định dạng</h2><ul className="c-check-list"><li>Giản thể hoặc phồn thể được sử dụng nhất quán, ngoại trừ trích dẫn cần giữ nguyên.</li><li>Dấu câu tiếng Trung và dấu câu Latin không bị trộn lẫn tùy tiện.</li><li>Tên riêng, phiên âm, viết hoa, thuật ngữ và chữ viết tắt thống nhất từ đầu đến cuối.</li><li>Font, cỡ chữ, lề, giãn dòng, đánh số trang và cấp tiêu đề khớp mẫu chính thức.</li><li>Ký tự lạ, lỗi font và khoảng trắng thừa đã được rà soát sau khi chuyển đổi tệp.</li></ul></section>
        <section><h2>3. Cấu trúc và mạch lập luận</h2><ul className="c-check-list"><li>Tiêu đề trong mục lục khớp chính xác với thân bài và số trang.</li><li>Tóm tắt nêu rõ bối cảnh, mục tiêu, phương pháp, kết quả chính và ý nghĩa.</li><li>Câu hỏi nghiên cứu, phương pháp, kết quả và kết luận liên kết với nhau.</li><li>Mỗi chương có mục tiêu rõ và không lặp lại nguyên đoạn của chương trước.</li><li>Kết luận không đưa vào dữ liệu hoặc khẳng định mới chưa được phân tích.</li></ul></section>
        <section><h2>4. Dữ liệu, bảng, hình và phụ lục</h2><ul className="c-check-list"><li>Bảng và hình có số, tên, nguồn và được nhắc đến trong thân bài.</li><li>Số liệu trong phần mô tả khớp với bảng, biểu đồ và kết quả phân tích.</li><li>Phương pháp thu thập, tiêu chí loại dữ liệu và phần mềm xử lý được mô tả đủ để hiểu.</li><li>Dữ liệu cá nhân đã được ẩn danh và xử lý theo yêu cầu đạo đức nghiên cứu.</li><li>Bảng hỏi, danh sách ngữ liệu hoặc tài liệu dài được đặt ở phụ lục khi phù hợp và vẫn ghi nguồn.</li></ul></section>
        <section><h2>5. Rà soát tương đồng bằng C-checker</h2><ul className="c-check-list"><li>Chuẩn bị tệp .txt, .docx hoặc .pdf có lớp văn bản đọc được; tệp scan ảnh có thể không trích xuất đúng nội dung.</li><li>Mở từng câu vàng hoặc cam và kiểm tra nguồn thay vì chỉ nhìn tỷ lệ toàn bài.</li><li>Ưu tiên câu trùng nguyên văn, câu ở phần phân tích và nhiều câu cùng liên quan một nguồn.</li><li>Không sửa thuật ngữ, dữ kiện thư mục hoặc câu trích hợp lệ chỉ để hạ phần trăm.</li><li>Kiểm tra lại sau khi chỉnh sửa và lưu báo cáo nếu cần làm minh chứng cho quá trình rà soát.</li></ul><p>C-checker dùng nguồn web có thể tìm và truy cập, không thay thế hệ thống hoặc quy trình chính thức của trường. Đọc <Link to="/kien-thuc/han-che-va-sai-so">hạn chế và sai số</Link> trước khi diễn giải kết quả.</p></section>
        <section><h2>6. Kiểm tra bản xuất cuối</h2><ul className="c-check-list"><li>Mở tệp cuối trên một thiết bị khác để kiểm tra font, mục lục, hình và ngắt trang.</li><li>Tên tệp, tên tác giả, mã sinh viên, tên giảng viên và phiên bản nộp đã chính xác.</li><li>Xóa nhận xét, track changes, ghi chú nội bộ và dữ liệu ẩn không cần thiết.</li><li>Giữ một bản sao cùng dữ liệu, nguồn và báo cáo tại vị trí an toàn.</li><li>Nộp đúng định dạng, cổng nhận bài và thời hạn được thông báo.</li></ul></section>
        <section><h2>Kết luận</h2><p>Checklist tốt không hứa loại bỏ mọi rủi ro, nhưng giúp phát hiện lỗi có hệ thống trước khi nộp. Hãy dành một lượt riêng cho nội dung, một lượt cho nguồn và một lượt cho bản xuất cuối thay vì cố kiểm tra tất cả trong vài phút.</p></section>
      </div>
    </div></article>
  );
}
